refactor/delete unused files
TransbankDevelopers/transbank-plugin-prestashop-webpay-rest pull request #87
Opened 2023-10-11 22:11 UTC by mvarlic

* remove unused files

2023-10-11 22:31 UTC, tribiec approved these changes

2023-10-11 22:41 UTC, tribiec approved these changes

2023-10-12 03:03 UTC, mastudillot requested changes
Check the code smell and add evidence that everything is working fine after deleting so many files

2023-10-12 14:51 UTC, isabellaahc approved these changes

2023-10-12 16:02 UTC, mastudillot approved these changes
LGTM

2023-10-12 16:03 UTC, merged